gems:
  - jekyll-sitemap

exclude:
  - '/vendor/'

title: 'Kiran Rao'
subtitle: "I'm a Canadian software engineer based in San Francisco. I enjoy programming, finance, photography, triathlons and cocktails."
email: 'hi@kiranrao.ca'
author: 'Kiran Rao'
description: 'Hi, my name is Kiran.'
url: 'https://kiranrao.ca'
markdown: kramdown
repo: 'https://github.com/Kiran-Rao/kiran-rao.github.io'
siteDirectory: 'https://github.com/Kiran-Rao/kiran-rao.github.io/tree/master'

# Exclude unpublished files from sitemap
defaults:
  - scope:
      path: 'unpublished/**/*.*'
    values:
      sitemap: false
  - scope:
      path: 'assets/**/*.*'
    values:
      sitemap: false

host: 0.0.0.0 # Local only
